apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: soda-test
  namespace: nada
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      rules:
      - application: nada-soda
        namespace: nada
  env:
    - name: SODA_CONFIG
      value: /var/run/configmaps/soda-config/config.yaml
    - name: SODA_CHECKS_FOLDER
      value: /var/run/configmaps/soda-checks
    - name: SLACK_CHANNEL
      value: "#kubeflow-cron-alerts"
  schedule: '11 5 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backoffLimit: 1
  concurrencyPolicy: Forbid
  filesFrom:
    - configmap: soda-checks
    - configmap: soda-config
  gcp:
    permissions:
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-dev-db2e
      role: roles/bigquery.readSessionUser
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-dev-db2e
      role: roles/bigquery.dataViewer
    - resource:
        apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
        kind: Project
        name: nada-dev-db2e
      role: roles/bigquery.jobUser
