apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: nada
data:
  doc_demo.yaml: |
    checks for go:
      - missing_count(stringValue) = 0
      - invalid_count(numericValue) = 0:
          valid min: 1
          valid max: 9
      - duplicate_count(timestampValue) = 0
    checks for py:
      - missing_count(stringValue) = 0
      - invalid_count(numericValue) = 0:
          valid min: 1
          valid max: 10
      - duplicate_count(timestampValue) = 0
  datastream_nada.yaml: |
    checks for public_datasets:
      - missing_count(dataproduct_id) = 1
      - missing_count(id) = 0
